name: Build and release native library

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Import signing certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        
      - name: Build
        run: |
          xcodebuild clean build -scheme JavaTouchBar-Release
          shasum -a 512 src/release/resources/lib/libJavaTouchBar.dylib
          
      - name: Create checksum
        id: create-checksum
        run: | 
          cd src/release/resources/lib
          shasum -a 512 libJavaTouchBar.dylib > ../../../../checksum.txt

      - name: Upload Checksum Artifact
        id: upload-checksum-artifact
        uses: actions/upload-artifact@v3
        with:
          name: checksum.txt
          path: checksum.txt

      - name: Upload Native Library Artifact
        id: upload-native-library-artifact
        uses: actions/upload-artifact@v3
        with:
          name: libJavaTouchBar.dylib
          path: src/release/resources/lib/libJavaTouchBar.dylib
